language: shell
os: linux

stages:
  - name: test
    if: tag IS NOT present
  - name: release
    if: tag IS present AND NOT fork

before_install:
  - curl -Lo coursier https://git.io/coursier-cli
  - chmod +x coursier

jobs:
  include:
    - stage: test
      name: Validate .scalafmt.conf file
      install: ./coursier bootstrap org.scalameta:scalafmt-cli_2.12:"[0.0.1,)" -f -o scalafmt --standalone --main org.scalafmt.cli.Cli
      script:
        - ./scalafmt --version
        - ./scalafmt --check > /dev/null 2>&1
    - stage: test
      name: Validate .scalafix.conf file
      install:
        - ./coursier bootstrap ch.epfl.scala:scalafix-cli_2.12.10:"[0.0.1,)" -f -o scalafix --standalone --main scalafix.cli.Cli
        - SCALUZZI="$(./coursier fetch -p com.github.vovapolu:scaluzzi_2.12:"[0.0.1,)")"
        - SORT_IMPORTS="$(./coursier fetch -p com.nequissimus:sort-imports_2.12:"[0.0.1,)")"
        - NO_INFER="$(./coursier fetch -p com.eed3si9n.fix:scalafix-noinfer_2.12:"[0.0.1,)")"
      script:
        - ./scalafix --version
        - ./scalafix --tool-classpath="$SCALUZZI:$SORT_IMPORTS:$NO_INFER" --scalac-options="-Ywarn-unused-import" --syntactic --check
    - stage: release
      name: Upload artifacts to Github Releases
      before_deploy:
        - rm -rf sbt-fix
        - git clone git://github.com/alejandrohdezma/sbt-fix.git
        - sed -i -e "s/version = \(.*\)/version = \"$TRAVIS_TAG\"/" sbt-fix/sbt-fix/src/main/scala/com/alejandrohdezma/sbt/fix/Defaults.scala
      deploy:
        - provider: releases
          edge: true
          token: $GITHUB_TOKEN
          file:
            - .scalafix.conf
            - .scalafmt.conf
          on:
            tags: true
        - provider: pages:git
          edge: true
          token: $GITHUB_TOKEN
          target_branch: master
          local_dir: sbt-fix
          repo: alejandrohdezma/sbt-fix
          commit_message: "Uploading sbt-fix-defaults version"
          on:
            tags: true

cache:
  directories:
    - "$HOME/.coursier"
    - "$HOME/.cache"
